# Generated by Django 5.0.6 on 2024-06-04 13:26

import datetime
import inventory_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=inventory_app.models.upload_to)),
                ('price', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 4, 13, 26, 16, 673564))),
                ('updated', models.DateTimeField(default=datetime.datetime(2024, 6, 4, 13, 26, 16, 673578))),
                ('is_avaliable', models.BooleanField(default=True)),
            ],
        ),
    ]
